version: "3.9"
services:
  db:
    image: "mysql:5.7"
    command: "--default-authentication-plugin=mysql_native_password"
    restart: "always"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: "printabrick"
  elastic:
    image: "docker.elastic.co/elasticsearch/elasticsearch:5.5.0"
    expose:
      - "9200"
      - "9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
  printabrick:
    build:
      context: .
    environment:
      - BRICKSET_API=
      - REBRICKABLE_API=
    ports:
      - "8000:8000"
    depends_on:
      - db
      - elastic
